# Generated by Django 3.1.5 on 2021-02-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('notes', models.BooleanField(default=False)),
                ('software', models.BooleanField(default=False)),
                ('certi', models.BooleanField(default=False)),
            ],
        ),
    ]
